/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PrivateIndexImport } from './routes/private/index'
import { Route as isAuthenticatedAuthImport } from './routes/(isAuthenticated)/_auth'
import { Route as QrcodenewViewPlanIndexImport } from './routes/qrcodenew/view-plan/index'
import { Route as authSignUpIndexImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexImport } from './routes/(auth)/sign-in/index'
import { Route as isAuthenticatedAuthDashboardIndexImport } from './routes/(isAuthenticated)/_auth/dashboard/index'
import { Route as isAuthenticatedAuthDashboardPlanPlanIdImport } from './routes/(isAuthenticated)/_auth/dashboard/plan/$planId'

// Create Virtual Routes

const isAuthenticatedImport = createFileRoute('/(isAuthenticated)')()

// Create/Update Routes

const isAuthenticatedRoute = isAuthenticatedImport.update({
  id: '/(isAuthenticated)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexRoute = PrivateIndexImport.update({
  id: '/private/',
  path: '/private/',
  getParentRoute: () => rootRoute,
} as any)

const isAuthenticatedAuthRoute = isAuthenticatedAuthImport.update({
  id: '/_auth',
  getParentRoute: () => isAuthenticatedRoute,
} as any)

const QrcodenewViewPlanIndexRoute = QrcodenewViewPlanIndexImport.update({
  id: '/qrcodenew/view-plan/',
  path: '/qrcodenew/view-plan/',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpIndexRoute = authSignUpIndexImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const authSignInIndexRoute = authSignInIndexImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const isAuthenticatedAuthDashboardIndexRoute =
  isAuthenticatedAuthDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => isAuthenticatedAuthRoute,
  } as any)

const isAuthenticatedAuthDashboardPlanPlanIdRoute =
  isAuthenticatedAuthDashboardPlanPlanIdImport.update({
    id: '/dashboard/plan/$planId',
    path: '/dashboard/plan/$planId',
    getParentRoute: () => isAuthenticatedAuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(isAuthenticated)': {
      id: '/(isAuthenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof isAuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(isAuthenticated)/_auth': {
      id: '/(isAuthenticated)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof isAuthenticatedAuthImport
      parentRoute: typeof isAuthenticatedRoute
    }
    '/private/': {
      id: '/private/'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/qrcodenew/view-plan/': {
      id: '/qrcodenew/view-plan/'
      path: '/qrcodenew/view-plan'
      fullPath: '/qrcodenew/view-plan'
      preLoaderRoute: typeof QrcodenewViewPlanIndexImport
      parentRoute: typeof rootRoute
    }
    '/(isAuthenticated)/_auth/dashboard/': {
      id: '/(isAuthenticated)/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof isAuthenticatedAuthDashboardIndexImport
      parentRoute: typeof isAuthenticatedAuthImport
    }
    '/(isAuthenticated)/_auth/dashboard/plan/$planId': {
      id: '/(isAuthenticated)/_auth/dashboard/plan/$planId'
      path: '/dashboard/plan/$planId'
      fullPath: '/dashboard/plan/$planId'
      preLoaderRoute: typeof isAuthenticatedAuthDashboardPlanPlanIdImport
      parentRoute: typeof isAuthenticatedAuthImport
    }
  }
}

// Create and export the route tree

interface isAuthenticatedAuthRouteChildren {
  isAuthenticatedAuthDashboardIndexRoute: typeof isAuthenticatedAuthDashboardIndexRoute
  isAuthenticatedAuthDashboardPlanPlanIdRoute: typeof isAuthenticatedAuthDashboardPlanPlanIdRoute
}

const isAuthenticatedAuthRouteChildren: isAuthenticatedAuthRouteChildren = {
  isAuthenticatedAuthDashboardIndexRoute:
    isAuthenticatedAuthDashboardIndexRoute,
  isAuthenticatedAuthDashboardPlanPlanIdRoute:
    isAuthenticatedAuthDashboardPlanPlanIdRoute,
}

const isAuthenticatedAuthRouteWithChildren =
  isAuthenticatedAuthRoute._addFileChildren(isAuthenticatedAuthRouteChildren)

interface isAuthenticatedRouteChildren {
  isAuthenticatedAuthRoute: typeof isAuthenticatedAuthRouteWithChildren
}

const isAuthenticatedRouteChildren: isAuthenticatedRouteChildren = {
  isAuthenticatedAuthRoute: isAuthenticatedAuthRouteWithChildren,
}

const isAuthenticatedRouteWithChildren = isAuthenticatedRoute._addFileChildren(
  isAuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof isAuthenticatedAuthRouteWithChildren
  '/private': typeof PrivateIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/qrcodenew/view-plan': typeof QrcodenewViewPlanIndexRoute
  '/dashboard': typeof isAuthenticatedAuthDashboardIndexRoute
  '/dashboard/plan/$planId': typeof isAuthenticatedAuthDashboardPlanPlanIdRoute
}

export interface FileRoutesByTo {
  '/': typeof isAuthenticatedAuthRouteWithChildren
  '/private': typeof PrivateIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/qrcodenew/view-plan': typeof QrcodenewViewPlanIndexRoute
  '/dashboard': typeof isAuthenticatedAuthDashboardIndexRoute
  '/dashboard/plan/$planId': typeof isAuthenticatedAuthDashboardPlanPlanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(isAuthenticated)': typeof isAuthenticatedRouteWithChildren
  '/(isAuthenticated)/_auth': typeof isAuthenticatedAuthRouteWithChildren
  '/private/': typeof PrivateIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/qrcodenew/view-plan/': typeof QrcodenewViewPlanIndexRoute
  '/(isAuthenticated)/_auth/dashboard/': typeof isAuthenticatedAuthDashboardIndexRoute
  '/(isAuthenticated)/_auth/dashboard/plan/$planId': typeof isAuthenticatedAuthDashboardPlanPlanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/private'
    | '/sign-in'
    | '/sign-up'
    | '/qrcodenew/view-plan'
    | '/dashboard'
    | '/dashboard/plan/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/private'
    | '/sign-in'
    | '/sign-up'
    | '/qrcodenew/view-plan'
    | '/dashboard'
    | '/dashboard/plan/$planId'
  id:
    | '__root__'
    | '/'
    | '/(isAuthenticated)'
    | '/(isAuthenticated)/_auth'
    | '/private/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/qrcodenew/view-plan/'
    | '/(isAuthenticated)/_auth/dashboard/'
    | '/(isAuthenticated)/_auth/dashboard/plan/$planId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  isAuthenticatedRoute: typeof isAuthenticatedRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
  QrcodenewViewPlanIndexRoute: typeof QrcodenewViewPlanIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  isAuthenticatedRoute: isAuthenticatedRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
  QrcodenewViewPlanIndexRoute: QrcodenewViewPlanIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(isAuthenticated)",
        "/private/",
        "/(auth)/sign-in/",
        "/(auth)/sign-up/",
        "/qrcodenew/view-plan/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(isAuthenticated)": {
      "filePath": "(isAuthenticated)",
      "children": [
        "/(isAuthenticated)/_auth"
      ]
    },
    "/(isAuthenticated)/_auth": {
      "filePath": "(isAuthenticated)/_auth.tsx",
      "parent": "/(isAuthenticated)",
      "children": [
        "/(isAuthenticated)/_auth/dashboard/",
        "/(isAuthenticated)/_auth/dashboard/plan/$planId"
      ]
    },
    "/private/": {
      "filePath": "private/index.tsx"
    },
    "/(auth)/sign-in/": {
      "filePath": "(auth)/sign-in/index.tsx"
    },
    "/(auth)/sign-up/": {
      "filePath": "(auth)/sign-up/index.tsx"
    },
    "/qrcodenew/view-plan/": {
      "filePath": "qrcodenew/view-plan/index.tsx"
    },
    "/(isAuthenticated)/_auth/dashboard/": {
      "filePath": "(isAuthenticated)/_auth/dashboard/index.tsx",
      "parent": "/(isAuthenticated)/_auth"
    },
    "/(isAuthenticated)/_auth/dashboard/plan/$planId": {
      "filePath": "(isAuthenticated)/_auth/dashboard/plan/$planId.tsx",
      "parent": "/(isAuthenticated)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
